clear all
close all
clc

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: ./combined_hourly_data.csv 
%
% Auto-generated by MATLAB on 03-Jun-2021 14:28:07

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["timestamp", "temp", "hum", "bar", "rain", "RSSI_01", "RSSI_02", "RSSI_03", "RSSI_04", "RSSI_05", "RSSI_06", "RSSI_07", "RSSI_08", "SNR_01", "SNR_02", "SNR_03", "SNR_04", "SNR_05", "SNR_06", "SNR_07", "SNR_08"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
meteo = readtable(".\combined_hourly_data.csv ", opts);

%% Convert to output type
meteo = table2array(meteo);

%% Clear temporary variables
clear opts

temp=meteo(:,2);
humid=meteo(:,3);
RSSI_01=meteo(:,6);
temp=round(temp);
humid=round(humid);

T=-4:15;
RSSImean=zeros(1,length(T));
for i=1:length(T)
    ind=find(temp==T(i));
    RSSImean(i)=mean(RSSI_01(ind),'omitnan');
end
figure(1),plot(RSSImean,T,'*');
xlabel('RSSI (dB)')
ylabel('Temperature (°C)')
grid on

H=[40:87];
RSSImean=zeros(1,length(H));
for i=1:length(H)
    ind=find(humid==H(i));
    RSSImean(i)=mean(RSSI_01(ind),'omitnan');
end
figure(2),plot(RSSImean,H,'*');
xlabel('RSSI (dB)')
ylabel('Relative Humidity (%)')
grid on

ahumid=(6.112*exp(17.67*temp./(temp+243.5)).*humid*2.1674)./(273.15+temp);
ahumid=round(ahumid*10);
ahumid=ahumid/10;
A=[1:96]/10;
RSSImean=zeros(1,length(A));
for i=1:length(A)
    ind=find(ahumid==A(i));
    RSSImean(i)=mean(RSSI_01(ind),'omitnan');
end
figure(3),plot(RSSImean,A,'*');
xlabel('RSSI (dB)')
ylabel('Absolute Humidity (g/m^3)')
grid on




